config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get "sessions/new"
  root "static_pages#home"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :locations
  resources :comments
  resources :tours do
    resources :locations, only: :index
  end
  resources :orders
  namespace :admin do
    root "static_pages#index"
    resources :users
    resources :hotels
    resources :tours
    resources :locations
    resources :sales
    resources :comments, only: %i(index destroy)
    resources :orders, except: :create
  end
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :tour
  has_many :orders, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  mount_uploader :picture, PictureUploader
  scope :select_column, -> {select :id, :name, :address, :description}
  scope :order_created_at_desc, -> {order created_at: :desc}
  scope :get_location_newest, -> {order(created_at: :desc).limit(Settings.maximum_newest)}
  scope :get_location_random, -> {order("RAND()").limit(Settings.maximum_newest)}
  scope :filter_by_tour, -> (tour_id){where(tour_id: tour_id)}
  scope :filter_by_name, -> (key){where("name LIKE ?", "%#{key}%")}
  scope :filter_by_duration, -> (duration){where("name LIKE ?", "%#{duration}%")}
  scope :filter_by_money, -> (money){where("name LIKE ?", "%#{money}%")}
end

app/controllers/admin/locations_controller.rb
module Admin
  class LocationsController < AdminBaseController
    before_action :load_location, only: %i(edit update destroy)

    def new
      @location = Location.new
    end

    def index
      @locations = Location.select_column.page(params[:page]).per Settings.paginate_perpage
    end

    def create
      @location = Location.new location_params
      if @location.save
        flash[:success] = t "admin.create.add_succ"
        redirect_to admin_locations_path
      else
        render :new
      end
    end

    def edit
      @location = Location.find_by id: params[:id]
    end

    def update
      @location = Location.find_by id: params[:id]
      if @location.update location_params
        flash[:success] = t "admin.update.edit_succ"
        redirect_to admin_locations_path
      else
        render :edit
      end
    end

    def destroy
      @location = Location.find_by id: params[:id]
      if @location.destroy
        flash[:success] = t "admin.destroy.delete_succ"
      else
        flash[:danger] = t "admin.destroy.delete_fail"
      end
      redirect_to admin_locations_path
    end

    private
    def location_params
      params.require(:location).permit :name, :address, :description, :tour_id, :picture
    end

    def load_location
      @location = Location.find_by id: params[:id]
      return if @location
      flash[:danger] = t "admin.edit.not_found"
      redirect_to admin_locations_path
    end

    def count_number index, page
      per_page = Settings.paginate_perpage
      count = (page-1)*per_page + index
    end
    helper_method :count_number
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @tour = Tour.find_by id: params[:tour_id]
    if @tour
      @locations = Location.filter_by_tour @tour
    elsif params[:search]
      @locations = Location.filter_by_name params[:search]
    else
      @locations = Location.all
    end
  end

  def show
    @location = Location.find_by id: params[:id]
    @locations = Location.filter_by_tour @location.tour_id
    comment = Comment.new
    @comments = Comment.get_comment.filter_by_location @location
  end
end

app/helpers/admin/locations_helper.rb
module Admin::LocationsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
  def tour
    Tour.pluck :name, :id
  end
end

app/views/admin/locations/edit.html.erb
<div class="col-md-6">
  <div class="content-box-large">
    <div class="panel-heading">
      <div class="panel-title"><%= t "admin.edit.edit_location" %></div>

      <div class="panel-options">
        <a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
        <a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
      </div>
    </div>
    <div class="panel-body">
      <%= form_for [:admin,@location] do |f| %>
        <fieldset>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :address %>
            <%= f.text_field :address, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :picture %>
            <%= image_tag @location.picture.url, class: "image-admin" %>
            <%= f.file_field :picture, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.cktext_area :description, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :tour_id, t("admin.new.tour") %>
            <%= f.select :tour_id, tour, class: "form-control" %>
          </div>
        </fieldset>
        <div>
            <%= f.submit t("admin.edit.edit_location"), class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/locations/index.html.erb
<div class="col-md-12">
  <div class="content-box-large">
    <div class="panel-heading">
      <div class="panel-title"><%= t "admin.index.list_location" %></div>
      <div class="panel-options">
        <a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
        <a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
      </div>
    </div>
    <div class="panel-body">
    <% flash.each do |key, value| %>
      <div class="row">
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      </div>
    <% end %>
      <table class="table table-hover">
        <tr>
          <th>#</th>
          <th><%= t "admin.index.name" %></th>
          <th><%= t "admin.index.address" %></th>
          <th><%= t "admin.index.action" %></th>
        </tr>
        <tbody>
          <% @locations.each_with_index do |location,index| %>
          <tr>
            <td><%= count_number index, @locations.current_page %></td>
            <td><%= location.name %></td>
            <td><%= location.address %></td>
            <td>
              <%= link_to edit_admin_location_path(location) do %>
                <i class="glyphicon glyphicon-pencil"></i>
              <% end %>
              <%= link_to admin_location_path(location) , method: :delete, data: {confirm: t("admin.index.you_sure")} do %>
                <i class="glyphicon glyphicon-trash"></i>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @locations, theme: "twitter-bootstrap-3" %>
    </div>
  </div>
</div>
</div>

app/views/admin/locations/new.html.erb
<div class="col-md-6">
  <div class="content-box-large">
    <div class="panel-heading">
      <div class="panel-title"><%= t "admin.new.add_location" %></div>

      <div class="panel-options">
        <a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
        <a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
      </div>
    </div>
    <div class="panel-body">
      <%= form_for [:admin,@location] do |f| %>
        <fieldset>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :address %>
            <%= f.text_field :address, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :picture %>
            <%= f.file_field :picture, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.cktext_area :description, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :tour_id, t("admin.new.tour") %>
            <%= f.select :tour_id, tour, class: "form-control" %>
          </div>
        </fieldset>
        <div>
            <%= f.submit t("admin.new.add_new"), class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>