config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get "sessions/new"
  root "static_pages#home"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :locations
  resources :comments
  resources :tours do
    resources :locations, only: :index
  end
  resources :orders
  namespace :admin do
    root "static_pages#index"
    resources :users
    resources :hotels
    resources :tours
    resources :locations
    resources :sales
    resources :comments, only: %i(index destroy)
    resources :orders, except: :create
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  has_many :locations, dependent: :destroy
  has_many :sales, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  mount_uploader :picture, PictureUploader
  scope :get_list_tour, -> {select :id, :name}
end

app/controllers/admin/tours_controller.rb
module Admin
  class ToursController < AdminBaseController
    before_action :load_tour, only: %i(edit update destroy)

    def index
      @tours = Tour.all
    end

    def new
      @tour = Tour.new
    end

    def create
      @tour = Tour.create tour_params
      if @tour.save
        flash[:success] = t "admin.create.add_succ"
        redirect_to admin_tours_path
      else
        render :new
      end
    end

    def edit; end

    def update
      if @tour.update tour_params
        flash[:success] = t "admin.update.edit_succ"
        redirect_to admin_tours_path
      else
        render :edit
      end
    end

    def destroy
      if @tour.destroy
        flash[:success] = t "admin.destroy.delete_succ"
      else
        flash[:danger] = t "admin.destroy.delete_fail"
      end
      redirect_to admin_tours_path
    end

    private
    def tour_params
      params.require(:tour).permit :name, :departureDay, :duration, :money, :schedule,
      :picture
    end

    def load_tour
      @tour = Tour.find_by id: params[:id]
      return if @tour
      flash[:danger] = t "admin.edit.not_found"
      redirect_to admin_tours_path
    end
  end
end

app/helpers/admin/tours_helper.rb
module Admin::ToursHelper
end

app/views/admin/tours/edit.html.erb
<div class="col-md-6">
  <div class="content-box-large">
    <div class="panel-heading">
      <div class="panel-title"><%= t "admin.edit.edit_tour" %></div>

      <div class="panel-options">
        <a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
        <a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
      </div>
    </div>
    <div class="panel-body">
      <%= form_for [:admin,@tour] do |f| %>
        <fieldset>
          <div class="form-group">
           <%= f.label :name %>
           <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
           <%= f.label :departureDay %>
           <%= f.date_field :departureDay, class: "form-control" %>
          </div>
          <div class="form-group">
           <%= f.label :duration %>
           <%= f.number_field :duration, class: "form-control" %>
          </div>
          <div class="form-group">
           <%= f.label :money %>
           <%= f.number_field :money, class: "form-control" %>
          </div>
          <div class="form-group">
           <%= f.label :schedule %>
           <%= f.text_field :schedule, class: "form-control" %>
          </div>
          <div class="form-group">
           <%= f.label :picture %>
           <%= image_tag @tour.picture.url, class: "image-admin" %>
           <%= f.file_field :picture, class: "form-control" %>
          </div>
        </fieldset>
        <div>
            <%= f.submit t("admin.edit.edit_tour"), class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/tours/index.html.erb
<div class="col-md-12">
  <div class="content-box-large">
    <div class="panel-heading">
      <div class="panel-title">List tour</div>
      <div class="panel-options">
        <a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
        <a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
      </div>
    </div>
    <div class="panel-body">
    <% flash.each do |key, value| %>
      <div class="row">
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      </div>
    <% end %>
      <table class="table table-hover">
        <tr>
          <th>#</th>
          <th><%= t "admin.index.name" %></th>
          <th><%= t "admin.index.departure" %></th>
          <th><%= t "admin.index.duration" %></th>
          <th><%= t "admin.index.money" %></th>
          <th><%= t "admin.index.action" %></th>
        </tr>
        <tbody>
          <% @tours.each_with_index do |tour, index| %>
          <tr>
            <td><%= index %></td>
            <td><%= tour.name %></td>
            <td><%= tour.departureDay %></td>
            <td><%= tour.duration %></td>
            <td><%= tour.money %></td>
            <td>
              <%= link_to edit_admin_tour_path(tour) do %>
                <i class="glyphicon glyphicon-pencil"></i>
              <% end %>
              <%= link_to admin_tour_path(tour), method: :delete, data: {confirm: t("admin.index.you_sure")} do %>
                <i class="glyphicon glyphicon-trash"></i>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>

app/views/admin/tours/new.html.erb
<div class="col-md-6">
  <div class="content-box-large">
    <div class="panel-heading">
      <div class="panel-title"><%= t "admin.new.add_tour" %></div>

      <div class="panel-options">
        <a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
        <a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
      </div>
    </div>
    <div class="panel-body">
      <%= form_for [:admin,@tour] do |f| %>
        <fieldset>
          <div class="form-group">
           <%= f.label :name %>
           <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
           <%= f.label :departureDay %>
           <%= f.date_field :departureDay, class: "form-control" %>
          </div>
          <div class="form-group">
           <%= f.label :duration %>
           <%= f.number_field :duration, class: "form-control" %>
          </div>
          <div class="form-group">
           <%= f.label :money %>
           <%= f.number_field :money, class: "form-control" %>
          </div>
          <div class="form-group">
           <%= f.label :schedule %>
           <%= f.text_field :schedule, class: "form-control" %>
          </div>
          <div class="form-group">
           <%= f.label :picture %>
           <%= f.file_field :picture, class: "form-control" %>
          </div>
        </fieldset>
        <div>
            <%= f.submit t("admin.new.add_new"), class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>