config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get "sessions/new"
  root "static_pages#home"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :locations
  resources :comments
  resources :tours do
    resources :locations, only: :index
  end
  resources :orders
  namespace :admin do
    root "static_pages#index"
    resources :users
    resources :hotels
    resources :tours
    resources :locations
    resources :sales
    resources :comments, only: %i(index destroy)
    resources :orders, except: :create
  end
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  validates :name, uniqueness: true
end

app/controllers/admin/hotels_controller.rb
module Admin
  class HotelsController < AdminBaseController
    before_action :hotel_params, only: %i(create update)
    before_action :find_hotel, only: %i(edit update destroy)

    def index
      @hotel = Hotel.all.page(params[:page]).per(5)
    end

    def new
      @hotel = Hotel.new
    end

    def create
      @hotel = Hotel.create hotel_params
      if @hotel.save
        flash[:success] = t "admin.create.create_hotel"
        redirect_to admin_hotels_path
      else
        render :new
      end
    end

    def edit; end

    def update
      if @hotel.update hotel_params
        flash[:success] = t "admin.update.edit_succ"
        redirect_to admin_hotels_path
      else
        render :edit
      end
    end

    def destroy
      if @hotel.destroy
        flash[:success] = t "admin.destroy.delete_succ"
      else
        flash[:danger] = t "admin.destroy.delete_fail"
      end
      redirect_to admin_hotels_path
    end

    private
    def hotel_params
      params.require(:hotel).permit :name, :address, :phone
    end

    def find_hotel
      @hotel = Hotel.find_by id: params[:id]
      return if @hotel
      flash[:danger] = "Cannot find hotel"
      redirect_to admin_hotels_path
    end
  end
end

app/helpers/admin/hotel_helper.rb
module Admin::HotelHelper
end

app/views/admin/hotels/edit.html.erb
<div class="col-md-6">
  <div class="content-box-large">
    <div class="panel-heading">
      <div class="panel-title"><%= t "admin.edit.edit" %></div>

      <div class="panel-options">
        <a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
        <a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
      </div>
    </div>
    <div class="panel-body">
      <%= form_for [:admin,@hotel] do |f| %>
        <fieldset>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :address %>
            <%= f.text_field :address, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :phone %>
            <%= f.text_field :phone, class: "form-control" %>
          </div>
        </fieldset>
        <div>
            <%= f.submit t("admin.new.add_new"), class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/hotels/index.html.erb
<div class="col-md-12">
  <div class="content-box-large">
    <div class="panel-heading">
      <div class="panel-title"><%= t "admin.index.list_hotel" %></div>
      <div class="panel-options">
        <a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
        <a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
      </div>
    </div>
    <div class="panel-body">
    <% flash.each do |key, value| %>
      <div class="row">
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      </div>
    <% end %>
      <table class="table table-hover">
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Adress</th>
          <th>Phone</th>
          <th>Action</th>
        </tr>
        <tbody>
          <% @hotel.each do |hotel| %>
          <tr>
            <td><%= hotel.id%></td>
            <td><%= hotel.name %></td>
            <td><%= hotel.address %></td>
            <td><%= hotel.phone %></td>
            <td>
              <%= link_to edit_admin_hotel_path(hotel) do %>
                <i class="glyphicon glyphicon-pencil"></i>
              <% end %>
              <%= link_to admin_hotel_path(hotel), method: :delete, data: {confirm: "Your sure"} do %>
                <i class="glyphicon glyphicon-trash"></i>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @hotel, theme: "twitter-bootstrap-3" %>
    </div>
  </div>
</div>
</div>

app/views/admin/hotels/new.html.erb
<div class="col-md-6">
  <div class="content-box-large">
    <div class="panel-heading">
      <div class="panel-title"><%= t "admin.new.add_hotel" %></div>

      <div class="panel-options">
        <a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
        <a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
      </div>
    </div>
    <div class="panel-body">
      <%= form_for [:admin,@hotel] do |f| %>
        <fieldset>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :address %>
            <%= f.text_field :address, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :phone %>
            <%= f.text_field :phone, class: "form-control" %>
          </div>
        </fieldset>
        <div>
            <%= f.submit t("admin.new.add_new"), class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>