config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get "sessions/new"
  root "static_pages#home"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :locations
  resources :comments
  resources :tours do
    resources :locations, only: :index
  end
  resources :orders
  namespace :admin do
    root "static_pages#index"
    resources :users
    resources :hotels
    resources :tours
    resources :locations
    resources :sales
    resources :comments, only: %i(index destroy)
    resources :orders, except: :create
  end
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :tour
  has_many :orders, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  mount_uploader :picture, PictureUploader
  scope :select_column, -> {select :id, :name, :address, :description}
  scope :order_created_at_desc, -> {order created_at: :desc}
  scope :get_location_newest, -> {order(created_at: :desc).limit(Settings.maximum_newest)}
  scope :get_location_random, -> {order("RAND()").limit(Settings.maximum_newest)}
  scope :filter_by_tour, -> (tour_id){where(tour_id: tour_id)}
  scope :filter_by_name, -> (key){where("name LIKE ?", "%#{key}%")}
  scope :filter_by_duration, -> (duration){where("name LIKE ?", "%#{duration}%")}
  scope :filter_by_money, -> (money){where("name LIKE ?", "%#{money}%")}
end

app/controllers/admin/locations_controller.rb
module Admin
  class LocationsController < AdminBaseController
    before_action :load_location, only: %i(edit update destroy)

    def new
      @location = Location.new
    end

    def index
      @locations = Location.select_column.page(params[:page]).per Settings.paginate_perpage
    end

    def create
      @location = Location.new location_params
      if @location.save
        flash[:success] = t "admin.create.add_succ"
        redirect_to admin_locations_path
      else
        render :new
      end
    end

    def edit
      @location = Location.find_by id: params[:id]
    end

    def update
      @location = Location.find_by id: params[:id]
      if @location.update location_params
        flash[:success] = t "admin.update.edit_succ"
        redirect_to admin_locations_path
      else
        render :edit
      end
    end

    def destroy
      @location = Location.find_by id: params[:id]
      if @location.destroy
        flash[:success] = t "admin.destroy.delete_succ"
      else
        flash[:danger] = t "admin.destroy.delete_fail"
      end
      redirect_to admin_locations_path
    end

    private
    def location_params
      params.require(:location).permit :name, :address, :description, :tour_id, :picture
    end

    def load_location
      @location = Location.find_by id: params[:id]
      return if @location
      flash[:danger] = t "admin.edit.not_found"
      redirect_to admin_locations_path
    end

    def count_number index, page
      per_page = Settings.paginate_perpage
      count = (page-1)*per_page + index
    end
    helper_method :count_number
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @tour = Tour.find_by id: params[:tour_id]
    if @tour
      @locations = Location.filter_by_tour @tour
    elsif params[:search]
      @locations = Location.filter_by_name params[:search]
    else
      @locations = Location.all
    end
  end

  def show
    @location = Location.find_by id: params[:id]
    @locations = Location.filter_by_tour @location.tour_id
    comment = Comment.new
    @comments = Comment.get_comment.filter_by_location @location
  end
end

app/helpers/admin/locations_helper.rb
module Admin::LocationsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
  def tour
    Tour.pluck :name, :id
  end
end

app/views/locations/_comment.html.erb
<div class="row text-center">
  <div class="col-md-3">
    <b><%= comment.user.name %>:</b>
  </div>
  <div class="col-md-6 text-left">
    <p><%= comment.content %></p>
  </div>
  <div class="col-md-3">
    <p><%= comment.created_at %></p>
    <% if logged_in? %>
    <% if current_user.id == comment.user_id %>
    <%= link_to comment_path(comment), method: :delete, data: {confirm: t("admin.index.you_sure")}, remote: :true, class: "destroy-order" do %>
    <span class="glyphicon glyphicon-trash"></span>
    <% end %>
    <% end %>
    <% end %>
  </div>
</div>
<hr>

app/views/locations/_location.html.erb
<% @comments.each do |comment| %>
<div class="row text-center">
  <div class="col-md-3">
    <b><%= comment.user.name %>:</b>
  </div>
  <div class="col-md-6 text-left">
    <p><%= comment.content %></p>
  </div>
  <div class="col-md-3">
    <p><%= comment.created_at %></p>
    <% if logged_in? %>
    <% if current_user.id == comment.user_id %>
    <%= link_to comment_path(comment), method: :delete, data: {confirm: t("admin.index.you_sure")}, remote: :true, class: "destroy-order" do %>
    <span class="glyphicon glyphicon-trash"></span>
    <% end %>
    <% end %>
    <% end %>
  </div>
</div>
<hr>
<% end %>

app/views/locations/index.html.erb
<% if @locations.any? %>
  <div class="container location">
    <div class="tourName">
    <% if @tour %>
      <h2><%= @tour.name %></h2>
    <% else %>
      <h2 class="text-center">All locations</h2>
    <% end %>
    </div>
    <div class="row">
    <%= form_tag locations_path, method: :get , class: "form-inline" do %>
      <p class="text-right"><%= text_field_tag :search, params[:search], class: "form-control"  %>
      <%= submit_tag "Search", :name=>nil, onclick: "return checkSearch()", class: "btn btn-success" %></p>
    <% end %>
    </div>
    <div class="row row-image">
     <% @locations.each do |location| %>
      <div class="three_img col-md-3">
        <%= link_to image_tag location.picture.url %>
        <div class="name_img">
          <p><%= link_to location.name, location_path(location) %></p>
        </div>
        <div class="left">
          <p><span><%= t ".time" %></span>: <%= location.tour.duration %>days</p>
        </div>
        <div class="right">
          <p><span><%= t ".money" %></span>: <%= location.tour.money %></p>
        </div>
      </div>
      <%end%>
    </div>
  </div>
<% else %>
  <p class="text-danger text-center">No data to display</p>
<% end %>

app/views/locations/show.html.erb
<div class="container show_location">
  <div class="row">
    <div class="col-md-8">
      <h1 class="text-center text-success"><%= t ".info_add" %> <%= @location.name %></h1>
      <% flash.each do |key, value| %>
      <div class="row">
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      </div>
      <% end %>
      <div class="row info-tour">
        <div class="col-md-6">
          <p><%= image_tag @location.tour.picture.url, class: "image-tour" %></p>
          <blockquote><%= @location.tour.name %>: <span class="text-danger"><%= @location.name %></span></blockquote>
        </div>
        <div class="col-md-6">
          <h2 class="text-center text-primary"><%= t ".money" %></h2>
          <h1 class="text-center money"><%= @location.tour.money %></h1>
          <h4 class="text-left"><span class="text-danger"><%= t ".time" %>: </span><%= @location.tour.duration %></h4>
          <h4 class="text-left"><span class="text-danger"><%= t ".schedule" %>: </span><%= @location.tour.schedule %></h4>
          <h4 class="text-left"><span class="text-danger"><%= t ".daydepart" %>: </span><%= @location.tour.departureDay %></h4>
        </div>
      </div>
      <div class="row text-center">
        <%= raw @location.description %>
      </div>
      <p class="text-center"><%= image_tag @location.picture.url %></p>
      <blockquote class="text-center">
      <p>Address: <span class="text-primary"><%= @location.address %></span></p>
      </blockquote>
      <div class="row row-center">
        <h2 class="text-primary text-center"><%= t ".book_tour" %></h2>
        <%= form_with url: orders_path, method: :post do |f| %>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :phone %>
            <%= f.text_field :phone, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :quantity, t(".number_ticket") %>
            <%= f.number_field :quantity, name: "order[quantity]", class: "form-control"  %>
          </div>
          <div class="form-group">
            <%= f.hidden_field :money, name: "order[money]", value: @location.tour.money, class: "form-control"  %>
            <% if logged_in? %>
            <%= f.hidden_field :user_id, name: "order[user_id]", value: current_user.id, class: "form-control"  %>
            <% end %>
            <%= f.hidden_field :location_id, name: "order[location_id]", value: @location.id, class: "form-control"  %>
          </div>
          <%= f.submit t(".book"), onclick: "return checkOrder()", class: "btn btn-primary" %>
        <% end %>
      </div>
      <div class="row">
        <%= form_with url: comments_path, remote: true, method: :post do |f| %>
        <div class="form-group">
            <%= f.label :content, t(".comment") %>
            <%= f.text_area :content, name: "comment[content]", size: "30x10", class: "form-control"  %>
            <% if logged_in? %>
            <%= f.hidden_field :user_id, name: "comment[user_id]", value: current_user.id, class: "form-control"  %>
            <% end %>
            <%= f.hidden_field :location_id, name: "comment[location_id]", value: @location.id, class: "form-control"  %>
        </div>
        <%= f.submit t(".comment"), onclick: "return checkComment()", class: "btn btn-primary" %>
        <% end %>
      </div>
      <hr>
      <p class="text-success">Lastest comment</p>
      <hr>
      <div id="comment_form">
        <%= render "locations/location" %>
      </div>
    </div>
    <div class="col-md-4 relate">
      <h3 class="text-center bg-primary"><%= t ".add_relate" %></h3>
      <% @locations.each do |l| %>
      <div class="row row-relate">
        <p class="text-center"><%= image_tag l.picture.url, class: "image-relate img-rounded" %></p>
        <p class="text-center"><%= link_to l.name, location_path(l) %></p>
      </div>
      <% end %>
    </div>
  </div>
</div>